// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iogslsmqccnuozqavvua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZ3Nsc21xY2NudW96cWF2dnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTg5MDksImV4cCI6MjA3MTc5NDkwOX0.lcnlwAnymvGZXxGV88WaE2U16csvqAjXYeEpl6gmylY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});